-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Classes"
(
    classes_id integer NOT NULL DEFAULT nextval('classis_classis_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT classis_pkey PRIMARY KEY (classes_id)
);

CREATE TABLE IF NOT EXISTS public."Family"
(
    family_id integer NOT NULL DEFAULT nextval('familia_familia_id_seq'::regclass),
    order_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    superorder_id integer,
    CONSTRAINT familia_pkey PRIMARY KEY (family_id)
);

CREATE TABLE IF NOT EXISTS public."Genus"
(
    genus_id integer NOT NULL DEFAULT nextval('genus_genus_id_seq'::regclass),
    family_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT genus_pkey PRIMARY KEY (genus_id)
);

CREATE TABLE IF NOT EXISTS public."Order"
(
    order_id integer NOT NULL DEFAULT nextval('ordo_ordo_id_seq'::regclass),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    subclass_id integer,
    CONSTRAINT ordo_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public."Species"
(
    species_id integer NOT NULL DEFAULT nextval('species_species_id_seq'::regclass),
    genus_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT species_pkey PRIMARY KEY (species_id)
);

CREATE TABLE IF NOT EXISTS public."Subclasses"
(
    subclass_id integer NOT NULL DEFAULT nextval('subclassis_subclassis_id_seq'::regclass),
    class_id integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT subclassis_pkey PRIMARY KEY (subclass_id)
);

CREATE TABLE IF NOT EXISTS public.species
(
    id serial NOT NULL,
    scientificname character varying(255) COLLATE pg_catalog."default",
    taxonrank character varying(255) COLLATE pg_catalog."default",
    family character varying(255) COLLATE pg_catalog."default",
    subfamily character varying(255) COLLATE pg_catalog."default",
    tribe character varying(255) COLLATE pg_catalog."default",
    subtribe character varying(255) COLLATE pg_catalog."default",
    genus character varying(255) COLLATE pg_catalog."default",
    subgenus text COLLATE pg_catalog."default",
    taxonremarks text COLLATE pg_catalog."default",
    CONSTRAINT species_pkey1 PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Family"
    ADD CONSTRAINT familia_ordo_id_fkey FOREIGN KEY (order_id)
    REFERENCES public."Order" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Genus"
    ADD CONSTRAINT genus_familia_id_fkey FOREIGN KEY (family_id)
    REFERENCES public."Family" (family_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Species"
    ADD CONSTRAINT species_genus_id_fkey FOREIGN KEY (genus_id)
    REFERENCES public."Genus" (genus_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Subclasses"
    ADD CONSTRAINT subclassis_classis_id_fkey FOREIGN KEY (class_id)
    REFERENCES public."Classes" (classes_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;